Dodat .gitignore
pfe-rs/zr-s-2024-simulator-saobracaja pull request #1
Opened 2024-03-27 21:12 UTC by najkela

2024-03-27 22:15 UTC, GojakMilica approved these changes, later dismissed
kul, reci drugu da ti appruvije

2024-03-27 22:19 UTC, djokjulapfe requested changes
Treba prvo dizajn da se čekinuje

2024-03-27 22:22 UTC, GojakMilica commented on Classes.py
> +class Wichle:
vehicle

2024-03-28 11:03 UTC, GojakMilica commented on Put.py
> +                    return
Metoda pomeri vozila ne treba da bude u klasi Put. Razbiti to u neku drugu klasu

2024-03-28 11:03 UTC, djokjulapfe approved these changes
Fali vam klasa "Mreza" iz dizajna. Ali ajde evo vam approve.

2024-03-28 11:13 UTC, GojakMilica approved these changes

2024-03-28 11:43 UTC, merged