Implementacija Prepreke
pfe-rs/zr-s-2024-simulator-saobracaja pull request #21
Opened 2024-03-28 20:53 UTC by samoN1k0la

2024-03-29 10:50 UTC, GojakMilica requested changes

2024-03-29 10:50 UTC, GojakMilica commented on mreza.py
> +                        queue.append(raskrsnica)
zasto je ovo trostruka petlja? sta se ovde desava? Napraviti funkciju koja za jedno vozilo odredjuje gde ce ono ici pa to ubaciti u ovu fju. Start simulacije ne treba da bude u klasi mreza nego u napravite novu klasu simulacije koja vodi racuna o eventovima.
Razbiti ovo

2024-03-29 11:18 UTC, samoN1k0la commented
Nisam jos uvek razbio tu trostruku petlju (trenutno to radim). Samo sam dodao funkcionalnost da proverava da li prepreka dozvoljava da vozilo prodje.

2024-03-29 11:22 UTC, GojakMilica commented on mreza.py
>      def start(self, vehicles):
isti komentar kao za prosli commit

2024-03-30 11:50 UTC, GojakMilica approved these changes

2024-03-30 11:50 UTC, GojakMilica commented on Simulacija.py
> +    def start(self):
Ovo nije resilo problem

2024-03-30 11:50 UTC, GojakMilica commented on Simulacija.py
> +    def start(self):
Na dobrom si putu

2024-03-30 11:50 UTC, GojakMilica commented on Vozilo.py
> +                        print(f"({putID}, {voziloID})")
ovo su dve iste for petlje

2024-03-30 11:50 UTC, GojakMilica commented on Vozilo.py
> +    def Uzmi_mesto_na_putu(self) -> int:
Zar ova funkcija ne utice na put?

2024-03-30 11:52 UTC, merged